export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const API_ERRORED = "API_ERRORED";
export const DATA_REQUESTED = "DATA_REQUESTED";


export const TIME_STARTED = "TIME_STARTED";
export const TIME_MAXOUT_SET = "TIME_MAXOUT_SET";
export const WORKOUT_CONFIGURATION_SET = "WORKOUT_CONFIGURATION_SET";
export const WORKOUT_SAVE = "WORKOUT_SAVE";
export const USER_SET = "USER_SET";
export const WORKOUTS_REQUESTED = "WORKOUTS_REQUESTED";
export const WORKOUTS_LOADED = "WORKOUTS_LOADED";
export const HOME_SET = "HOME_SET";
export const TOKEN_SET = "TOKEN_SET";
